Fixing another test failure in Python 3.5
My guess is that newer version of Python doesn't actually check if this
path exists or not so it was masking this problem.

```
ERROR: test_subset_without_session (tests.test_runners.test_gradle.GradleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cli/cli/tests/helper.py", line 9, in do_test
    test_func(self, *args, **kwargs)
  File "<string>", line 3, in wrapper
  File "/home/runner/work/cli/cli/tests/test_runners/test_gradle.py", line 24, in test_subset_without_session
    self.build_name, 'gradle', str(self.test_files_dir.joinpath('java/app/test').resolve()))
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/pathlib.py", line 1109, in resolve
    s = self._flavour.resolve(self)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/pathlib.py", line 330, in resolve
    return _resolve(base, str(path)) or sep
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/pathlib.py", line 315, in _resolve
    target = accessor.readlink(newpath)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/pathlib.py", line 422, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/cli/cli/tests/data/gradle/java/app/test'
```