fix: validate build name format not to include forward slash
The specified build name is used as a part of request path as follows:

https://{API_ENDPOINT}/intake/organizations/{ORGANIZATION_NAME}/workspaces/{WORKSPACE_NAME}/builds/{BUILD_NAME}/{SESSION_NAME}

When specifying the build name including forward slashes, GET build requests
fail due to an unexpected build name or session name.

```
LAUNCHABLE_TOKEN=xxxx pipenv run launchable record tests --build 'tw/my-build-name' go-test report.xml
Build tw/my-build-name was not found. Make sure to run `launchable record build --name tw/my-build-name` before
404 Client Error:  for url: https://{API_ENDPOINT}/intake/organizations/{ORGANIZATION_NAME}/workspaces/{WORKSPACE_NAME}/builds/tw/my-build-name/test_sessions
Build tw/my-build-name was not found. Make sure to run `launchable record build --name tw/my-build-name` before `launchable record tests`
Traceback (most recent call last):
  File "/Users/username/.local/share/virtualenvs/launchable-go-qooJbKhC/lib/python3.9/site-packages/launchable/commands/record/tests.py", line 283, in run
    send(p)
  File "/Users/username/.local/share/virtualenvs/launchable-go-qooJbKhC/lib/python3.9/site-packages/launchable/commands/record/tests.py", line 250, in send
    elif build_name:
NameError: free variable 'build_name' referenced before assignment in enclosing scope
```