Fix TypeError in float() argument
The way CaseEvent.create works, it creates a dict with a key 'duration' and `None` as the value, which is different from a dict not having the key:

```
>>> x={"duration":None}
>>> "duration" in x
True
```

I believe it's more idiomatic to use "get(key) or 0" to fall back, which handles both cases correctly, whether the value is false-ish or the key is not present.

```
Traceback (most recent call last):
  File "/home/go/.local/bin/launchable", line 8, in <module>
    sys.exit(main())
  File "/home/go/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/go/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/go/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/go/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/go/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/go/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/go/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/go/.local/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/go/.local/lib/python3.7/site-packages/launchable/test_runners/launchable.py", line 123, in record_tests
    client.run()
  File "/home/go/.local/lib/python3.7/site-packages/launchable/commands/record/tests.py", line 314, in run
    test_count, success_count, fail_count, duration = recorded_result()
  File "/home/go/.local/lib/python3.7/site-packages/launchable/commands/record/tests.py", line 273, in recorded_result
    duration += float(tc["duration"])  # sec
TypeError: float() argument must be a string or a number, not 'NoneType'
```